script: |
  cd ~

  if [ ! -d "static-website" ]; then
    git clone https://github.com/Vyshnavipriya259/static-website.git
  else
    cd static-website
    git fetch --all
    git reset --hard origin/main
    cd ..
  fi

  cd static-website

  sudo docker stop mycontainer || true
  sudo docker rm mycontainer || true

  sudo docker build -t mywebsite .
  sudo docker run -d -p 80:80 --name mycontainer mywebsite
