name: Deploy Docker Website to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Go to home directory
            cd /home/ec2-user

            # Clone repo if not exists
            if [ ! -d "static-website" ]; then
              git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git
            fi

            # Go inside project folder
            cd static-website

            # Pull latest code
            git pull origin main

            # Stop and remove old container
            sudo docker stop mycontainer || true
            sudo docker rm mycontainer || true

            # Rebuild Docker image
            sudo docker build -t mywebsite .

            # Run new container
            sudo docker run -d -p 80:80 --name mycontainer mywebsite
